### PR TITLE
add trending component

### PR DESCRIPTION
**Pull request by NadiaFrShLm**
Add Trending Component #77
https://github.com/appwex/react-ui-components/issues/77#issue-1502488443

Screenshot Light Mode
Screenshot Dark Mode

- add **trending** folder to the **component** folder

- add import line of the component to **index.js**
     import Trending from 'components/trending/trending'

- add children element for const **router** to **index.js**
      {
        path: 'stories/trending',
        element: <Trending />,
      },

- add link to **trending** component at **story-page.jsx**
       <Link to={'/stories/trending'}>Trending</Link>

- add .png files to **assets** -> **images** folder (artwork1.png, artwork2.png, artwork3.png, artwork4.png, avatar-artwork1.png, avatar-artwork2.png, avatar-artwork3.png, avatar-artwork4.png)

- add .svg files to **assets** -> **svg**  folder (arrows.svg, heart.svg)

### CODE REVIEW

**Review by mrxshinji — APPROVED** [review]
I see there is repeating component for the 4 artwork. I believe it is better to create another component in the same folder for the repeating component so that in for any changes, you only need to change 1 set of code instead of all 4. Theres nothing wrong with this. But could be refactor better

Excellent PR.

**Comment by NadiaFrShLm** [comment]
I'll do my my best

**Comment by NadiaFrShLm** [comment]
add **artwork** cpomponent to the **trending** folder

import Artwork component with props for every artwork card.

Not sure if it's a right approach

**Review by mrxshinji — APPROVED** [review]
Excellent PR

**Pull request merged**
