### PR TITLE
Fixed #3 clean app

### LINKED ISSUE #3: Clean up React App
Clean up the app to build something new. We just need a blank page to start. There is a react spinner on the homepage which we won't need.

### PR DESCRIPTION
**Pull request by mrxshinji**
Fixes #3

Clean react-app

### CODE REVIEW

**Comment by aftabrehan** [comment]
@mrxshinji please also attach a screenshot, if it is possible.

**Comment by mrxshinji** [comment]
screenshot of ?

**Comment by aftabrehan** [comment]
> screenshot of ?

It could be the screenshot of the page preview, or if you made a component you can attach a screenshot of it, so it would be easier to see what have you done.

**Comment by mrxshinji** [comment]
screnshot1

**Review by aftabrehan — APPROVED** [review]
Excellent PR, @mrxshinji 💪 🚀 💯

**Pull request merged**
